# Generated by Django 3.2.5 on 2021-08-06 16:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('graph_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('graph', models.ImageField(blank=True, null=True, upload_to='files/')),
                ('turns', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('money', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)])),
                ('bet', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
            ],
            options={
                'verbose_name_plural': 'graphs',
            },
        ),
    ]
